### ISSUE TITLE
Error when providing single input genome in FASTA format and multiple threads

### ISSUE THREAD

**Issue by rfm-targa** [tkchafin/mrbait#20]
Greetings,

Thank you for developing this software. It has a lot of options that simplify probe design and the option to resume allows to fine-tune the results and work towards a set of probes that fit my experiment.

I have encountered an error when I run MrBaits with a single input genome in FASTA format and specify that it can use 6 threads.
The text and traceback outputted are as follows:

```
$ mrbait -A GCF_000817005.1_ASM81700v1_genomic.fna -b 120 -T 6

        =======================================================================
            MrBait: Universal Probe Design for Targeted-Enrichment Methods
        =======================================================================

        Version:  1.1.6
        Author:   Tyler K. Chafin
        Contact:  tkchafin@uark.edu
        License:  GNU Public License v3.0

        Releases: https://github.com/tkchafin/mrbait/releases

        Citation: Chafin TK, Douglas MR, Douglas ME. 2018. MrBait: Universal
                identification and design of targeted-enrichment capture probes.
                Bioinformatics. https://doi.org/10.1093/bioinformatics/bty548

        Source code: https://github.com/tkchafin/mrbait
        Documentation: https://mrbait.readthedocs.io/
        Conda package: https://anaconda.org/tylerkchafin/mrbait

        =======================================================================


        Parsing command line arguments...
        Loading SQLite Database...
                Establishing database connection: /home/rfm/Lab_Analyses/baits_design/baits.sqlite
                Initializing empty tables.

                ### Runtime: 0:00:00 (0.077249 seconds) ###

        Step 1: Loading Alignments
                Step 1 parameters:
                        Minimum contig length (-l,--len): 120
                        Maximum allowed gap/N bases (-Q): 0.5
                        Maximum allowed masked bases (-K): 0.5
                Loading FASTA file: GCF_000817005.1_ASM81700v1_genomic.fna
                Filtering loci... Done!

                ### Results: 1 loci passed filtering! ###
                ### Runtime: 0:00:00 (0.652001 seconds) ###

        Step 2: Target Discovery
                Step 2 parameters:
                        Sliding window width (-b, --bait): 120
                        Sliding window shift distance (-w, --win_shift): 1
                        Variable columns allowed per target (-v, --var_max): 0
                        Ambiguities (N's) allowed per target (-n, --numN): 0
                        Gap characters allowed per target (-g, --numG): 0
                        Flanking distance to parse (-d,--flank_dist): 500
                Starting sliding window target discovery of 1 loci...
                        Finding targets using 6 parallel processes...
Traceback (most recent call last):
  File "/home/rfm/Software/anaconda3/envs/mrbaits/bin/mrbait", line 11, in <module>
    load_entry_point('mrbait==1.1.6', 'console_scripts', 'mrbait')()
  File "/home/rfm/Software/anaconda3/envs/mrbaits/lib/python3.7/site-packages/mrbait/mrbait.py", line 95, in main
    targetDiscovery(conn, params)
  File "/home/rfm/Software/anaconda3/envs/mrbaits/lib/python3.7/site-packages/mrbait/mrbait.py", line 276, in targetDiscovery
    pcore.targetDiscoverySlidingWindow_parallel(conn, params, passedLoci)
  File "/home/rfm/Software/anaconda3/envs/mrbaits/lib/python3.7/site-packages/mrbait/mrbait_corefuncs_parallel.py", line 335, in targetDiscoverySlidingWindow_parallel
    df_chunk.to_hdf(chunk_file, "NULL", mode="w", format="f")
  File "/home/rfm/Software/anaconda3/envs/mrbaits/lib/python3.7/site-packages/pandas/core/generic.py", line 2449, in to_hdf
    encoding=encoding,
  File "/home/rfm/Software/anaconda3/envs/mrbaits/lib/python3.7/site-packages/pandas/io/pytables.py", line 268, in to_hdf
    path_or_buf, mode=mode, complevel=complevel, complib=complib
  File "/home/rfm/Software/anaconda3/envs/mrbaits/lib/python3.7/site-packages/pandas/io/pytables.py", line 534, in __init__
    tables = import_optional_dependency("tables")
  File "/home/rfm/Software/anaconda3/envs/mrbaits/lib/python3.7/site-packages/pandas/compat/_optional.py", line 110, in import_optional_dependency
    raise ImportError(msg) from None
ImportError: Missing optional dependency 'tables'.  Use pip or conda to install tables.
```

If I run the same command with a single thread it seems to work as expected.

I would also like to ask about providing multiple genomes in FASTA format as input. Is it possible to provide more than 1 assembly FASTA file to the `-A` argument?
I tried to pass several assemblies with the following command:

```
mrbait -A *.fna -b 120 -T 6
```

It finished but the text outputted to the stdout seems to indicate that it only used 1 assembly and that it ignored the probe length value of 120 passed to the `-b` argument.
The text outputted to the stdout was the following:

```
        =======================================================================
            MrBait: Universal Probe Design for Targeted-Enrichment Methods
        =======================================================================

        Version:  1.1.6
        Author:   Tyler K. Chafin
        Contact:  tkchafin@uark.edu
        License:  GNU Public License v3.0

        Releases: https://github.com/tkchafin/mrbait/releases

        Citation: Chafin TK, Douglas MR, Douglas ME. 2018. MrBait: Universal
                identification and design of targeted-enrichment capture probes.
                Bioinformatics. https://doi.org/10.1093/bioinformatics/bty548

        Source code: https://github.com/tkchafin/mrbait
        Documentation: https://mrbait.readthedocs.io/
        Conda package: https://anaconda.org/tylerkchafin/mrbait

        =======================================================================


        Parsing command line arguments...
        Loading SQLite Database...
                Establishing database connection: /home/rfm/Lab_Analyses/baits_design/baits.sqlite
                Initializing empty tables.

                ### Runtime: 0:00:00 (0.078374 seconds) ###

        Step 1: Loading Alignments
                Step 1 parameters:
                        Minimum contig length (-l,--len): 80
                        Maximum allowed gap/N bases (-Q): 0.5
                        Maximum allowed masked bases (-K): 0.5
                Loading FASTA file: GCF_000817005.1_ASM81700v1_genomic.fna
                Filtering loci... Done!

                ### Results: 1 loci passed filtering! ###
                ### Runtime: 0:00:00 (0.642983 seconds) ###

        Step 2: Target Discovery
                Step 2 parameters:
                        Sliding window width (-b, --bait): 80
                        Sliding window shift distance (-w, --win_shift): 1
                        Variable columns allowed per target (-v, --var_max): 0
                        Ambiguities (N's) allowed per target (-n, --numN): 0
                        Gap characters allowed per target (-g, --numG): 0
                        Flanking distance to parse (-d,--flank_dist): 500
                Starting sliding window target discovery of 1 loci...

                ### Results: 1 potential targets identified! ###
                ### Runtime: 0:00:29 (29.472186 seconds) ###

        Step 3: Target Filtering and Selection
                Step 3 parameters:
                        Multiple targets allowed per locus (-R, --mult_reg): False
                        Flanking distance for target selection (-d,--flank_dist): 500
                Applying filters to 1 targets.
                        No filtering criteria provided. Retaining all targets.
                Resolving conflicting targets... Found 1 needing resolution.
                        Selection criterion (-S, --select_r): Random selection

                ### Results: 1 targets passed filtering! ###
                ### Runtime: 0:00:00 (0.026822 seconds) ###

        Step 4: Bait discovery
                Step 4 parameters:
                        Bait length (-b, --blen): 80
                        Tiling baits with 40 base overlap

                ### Results: 57193 potential baits identified! ###
                ### Runtime: 0:09:10 (550.034072 seconds) ###

        Step 5: Bait filtering
                Found 57193 potential baits!
                Applying filters to 57193 baits...
                        No filtering criteria provided. Retaining all baits.
                         57193 passed filtering.
                Formatting for printing...
                Final baits output to: /home/rfm/Lab_Analyses/baits_design/baits.fasta

                ### Results: 57193 baits output to file! ###
                ### Runtime: 0:00:05 (5.092945 seconds) ###

        =======================================================================
        ### Final output: /home/rfm/Lab_Analyses/baits_design/baits.fasta ###
        ### Runtime: 0:09:45 (585.347977 seconds) ###
```

It seems like it only used 1 of the assemblies and determined probes with 80bps and not 120bps.
Is it possible to pass more than 1 assembly in FASTA file? Should I provide information about variability from other genomes through a VCF file? Or is it limited to a single FASTA and to work with more genomes it is necessary to pass a MSA file to identify conserved and variable regions? I read the Docs but could not find an example or information about this usage case.

Thank you in advance!

rfm

**Comment by tkchafin** [comment]
Hi Rafael, 

Glad you're finding the code useful. Firstly, it looks like you're running v1.1.6 -- the current version is v1.2.6. There's a LOT of bug fixes in between those versions, and I think since then I've fixed the issue with the bait length argument. 

The first chunk of output you provided suggests you're missing the tables dependency. There was an incompatibility issue with conda for numpy and pyTables, so in v1.2.6 I fixed it. Updating should fix the bait-length issue as well as give you access to some new functionalities added since v1.1.6: https://github.com/tkchafin/mrbait/blob/master/CHANGELOG.md. 

The second issue (multiple FASTA) is unfortunately not possible right now since mrbait does not provide any alignment itself. The FASTA is intended to accompany a VCF file containing variants. To import data for your multiple genomes, there are several options: 

1) Summarize polymorphisms of your genomes as a VCF by mapping/ variant calling against your chosen reference. The reference can then be passed with -A, with an accompanying VCF passed with -V. This is useful because you can then also provide feature data from a GFF file with -F
2) There are several MSA options for import, so you could use either of those: Multiple Alignment Format (.maf) with -M; or eXtended Multi Fasta (.xmfa) using -X. 

Tyler

**Comment by rfm-targa** [comment]
Hello @tkchafin ,

Thank you for your response. I had not noticed that MrBait's version in my environment was v1.1.6. I installed through conda but it seems that it chose v1.1.6 to install, instead of v1.2.6. I tried to force installation of v1.2.6 and got the following stdout from conda:

```
$ conda install -c tylerkchafin mrbait=1.2.6

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                               
                                                                                                                                     
UnsatisfiableError: The following specifications were found to be incompatible with each other:                                      



Package python conflicts for:
python=3.7
python=3.7
Package ca-certificates conflicts for:
mrbait=1.2.6 -> python[version='3.6.*,>=3.6'] -> openssl[version='>=1.0.2p,<1.0.3a'] -> ca-certificates
python=3.7 -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
Package mmtf-python conflicts for:
mrbait=1.2.6 -> pandas[version='>=0.22'] -> mmtf-python
Package python_abi conflicts for:
python=3.7 -> pip -> setuptools -> python_abi=3.7[build=*_cp37m]
Package setuptools conflicts for:
python=3.7 -> pip -> setuptools
mrbait=1.2.6 -> setuptools
Package msgpack-python conflicts for:
mrbait=1.2.6 -> biopython -> mmtf-python -> msgpack-python
Package biopython conflicts for:
mrbait=1.2.6 -> biopython
Package certifi conflicts for:
mrbait=1.2.6 -> certifi
python=3.7 -> pip -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
mrbait=1.2.6 -> setuptools -> certifi[version='>=2016.09|>=2016.9.26']
```

My environment had Python 3.7 and that was causing some conflicts. After creating an environment with Python 3.6 it installed MrBait's v1.2.6 without any issues. I do not know if this will happen with other users that try to use Python > 3.6, but I hope it is helpful to you if it really is a general issue.

I managed to run MrBait v1.2.6 with one input assembly and 6 threads. Thank you a lot for providing some information about input data. I will continue to explore several options and ask if I have any doubts.

Thank you,

rfm

**Comment by rfm-targa** [comment]
Hi @tkchafin ,

I have been exploring MrBait to determine the options that will help me get the set of baits I need.
In the `Bait filtering` step I want to filter out baits, based on the `--filter_b blast_x=[i,q]` option, that align well against a genome that I passed to `--fastadb`. Based on the documentation (`"blast_x=[i,q]: Remove hits over "i" identity and "q" query coverage to provided db"`), I was expecting it to filter out baits that align well against the sequences provided to create the BLASTdb. However, BLAST seems to be reporting the following results:

```
  qseqid         sseqid  pident     qlen   length  evalue   bitscore  sstart     send  qcov
0   id_1  NZ_CP007593.1   100.0  2287774  2287774     0.0  4126000.0       1  2287774   1.0
```

I passed the input genome to filter out baits to test the results and expected it to determine that the baits are really similar to the genome in the BLASTdb and remove all/most baits, but the BLAST results indicate that it is aligning the target against the BLASTdb. Based on the results it does not filter out any baits. Can you provide any guidance on what I might be doing wrong and how I can filter out baits that match the sequence in the BLASTdb?

Thank you in advance,

rfm

**Comment by tkchafin** [comment]
Could you please provide the full output and full command-line call?

**Comment by rfm-targa** [comment]
Hello @tkchafin ,

Command and stdout:

```
$ mrbait -A GCF_000817005.1_ASM81700v1_genomic.fna -b 120 -T 6 --filter_b blast_x=0.8,0.8 --fastadb GCF_000817005.1_ASM81700v1_genomic.fna

        =======================================================================
            MrBait: Universal Probe Design for Targeted-Enrichment Methods
        =======================================================================

        Version:  1.2.6
        Author:   Tyler K. Chafin
        Contact:  tkchafin@uark.edu
        License:  GNU Public License v3.0

        Releases: https://github.com/tkchafin/mrbait/releases

        Citation: Chafin TK, Douglas MR, Douglas ME. 2018. MrBait: Universal
                identification and design of targeted-enrichment capture probes.
                Bioinformatics. https://doi.org/10.1093/bioinformatics/bty548

        Source code: https://github.com/tkchafin/mrbait
        Documentation: https://mrbait.readthedocs.io/
        Conda package: https://anaconda.org/tylerkchafin/mrbait

        =======================================================================


        Parsing command line arguments...
        Loading SQLite Database...
                Establishing database connection: /home/rfm/Lab_Analyses/baits_design/baits.sqlite
                Initializing empty tables.

                ### Runtime: 0:00:00 (0.075192 seconds) ###

        Step 1: Loading Alignments
                Step 1 parameters:
                        Minimum contig length (-l,--len): 120
                        Maximum allowed gap/N bases (-Q): 0.5
                        Maximum allowed masked bases (-K): 0.5
                Loading FASTA file: GCF_000817005.1_ASM81700v1_genomic.fna
                Filtering loci... Done!

                ### Results: 1 loci passed filtering! ###
                ### Runtime: 0:00:00 (0.685061 seconds) ###

        Step 2: Target Discovery
                Step 2 parameters:
                        Sliding window width (-b, --bait): 120
                        Sliding window shift distance (-w, --win_shift): 1
                        Variable columns allowed per target (-v, --var_max): 0
                        Ambiguities (N's) allowed per target (-n, --numN): 0
                        Gap characters allowed per target (-g, --numG): 0
                        Flanking distance to parse (-d,--flank_dist): 500
                Starting sliding window target discovery of 1 loci...
                        Finding targets using 6 parallel processes...

                ### Results: 1 potential targets identified! ###
                ### Runtime: 0:00:40 (40.959356 seconds) ###

        Step 3: Target Filtering and Selection
                Step 3 parameters:
                        Multiple targets allowed per locus (-R, --mult_reg): False
                        Flanking distance for target selection (-d,--flank_dist): 500
                Applying filters to 1 targets.
                        No filtering criteria provided. Retaining all targets.
                Resolving conflicting targets... Found 1 needing resolution.
                        Selection criterion (-S, --select_r): Random selection

                ### Results: 1 targets passed filtering! ###
                ### Runtime: 0:00:00 (0.032958 seconds) ###

        Step 4: Bait discovery
                Step 4 parameters:
                        Bait length (-b, --blen): 120
                        Tiling baits with 60 base overlap

                ### Results: 38128 potential baits identified! ###
                ### Runtime: 0:05:49 (349.349264 seconds) ###

        Step 5: Bait filtering
                Found 38128 potential baits!
                Applying filters to 38128 baits...
                        Filtering criterion: BLAST exclusion
                          --blastn path: blastn
                          --Database: /home/rfm/Lab_Analyses/baits_design/blastdb/baits
                          --Percent identity: 0.8
                          --Query coverage: 0.8
                          --N threads: 6
                          --Word size 11
                          --Gap open penalty: 5
                          --Gap extend: 2
                          --E-value cutoff: 1e-06
                          --DUST: True
                          --Method: blastn
                         38128 passed filtering.
                Formatting for printing...
                Final baits output to: /home/rfm/Lab_Analyses/baits_design/baits.fasta

                ### Results: 38128 baits output to file! ###
                ### Runtime: 0:00:26 (26.610779 seconds) ###

        =======================================================================
        ### Final output: /home/rfm/Lab_Analyses/baits_design/baits.fasta ###
        ### Runtime: 0:06:57 (417.713411 seconds) ###
```

Thank you,

rfm

**Comment by tkchafin** [comment]
Hi Rafael, 

You're correct - it looks like mrbait is running the blast_x filter on the target database, and NOT the baits, which obviously is incorrect. I've identified the bug in the code and will be pushing a fix (v1.2.7) very shortly after I finish testing it. 

Sorry about that! It looks like I introduced this bug a few version updates ago when I was messing with adding the blast_i and blast_a filters :(

Tyler

**Comment by tkchafin** [comment]
OK, I've added a new release v1.2.7 which fixes this bug. Testing it exactly as you used (with the GCF_000817005.1_ASM81700v1_genomic.fna) allows 2 baits to pass -- this is because of the DUST masking blastn does by default. To turn this off, use --nodust in your mrbait command call. For any blast_x filters you'll probably want the --nodust option set. 

v1.2.7 should update on conda shortly.

**Comment by rfm-targa** [comment]
Thank you a lot for solving this issue!

**Comment by tkchafin** [comment]
No problem, let me know if you run into any other problems.
